### ISSUE TITLE
Add image link to banner

### ISSUE THREAD

**Issue by edalzell** [silentzco/eileen200#1]
Please update the `feature/banner-link` branch and update the banner image link:

- [ ] enable 3 sizes, the one I have set already is the medium one, please make a small and large option
- [ ] handle the responsive part, scaling/moving as appropriate
- [ ] let me know what the sizes you used for the images are (so the client can make the images)

**Comment by edalzell** [comment]
@Krzemo @ArtyomDanilov here's the simple responsive work for Vegas Healthcare

**Comment by edalzell** [comment]
> @edalzell
> Can you explain please what you mean in 'handle the responsive part, scaling/moving as appropriate'?

Sure, thanks for asking for clarification. Right now it l looks fine for one image size on desktop, but if you shrink the browser you'll see it doesn't look great at smaller breakpoints.

I'd like it to look good for 3 image sizes at all the standard breakpoints.

**Comment by ArtyomDanilov** [comment]
@edalzell 
Sure!
I saw that the image_link fieldset is pinned to header. When some image is added, then logo, image and hamburger are in the same row and on mobile it looks not so good. Should I worry this? or just adjust this section to the content builder?

**Comment by edalzell** [comment]
> When some image is added, then logo, image and hamburger are in the same row and on mobile it looks not so good.

Exactly, this is what I was hoping you could fix. I did the CSS for the image, which is why it doesn't work, lol.

Please make it look good (at the 3 diff image sizes) at all existing breakpoints.

**Comment by ArtyomDanilov** [comment]
@edalzell 
Done.
All magic is on feature/banner-link

**Comment by edalzell** [comment]
Fixed in https://github.com/VegasHC/eileen200/pull/20
